parameters:
  net_name : poc-net
  net_cidr: 10.10.30.0/24
  net_gateway : 10.10.30.1
  net_pool_start : 10.10.30.10
  net_pool_end : 10.10.30.200
  ext_net_name : ext_net
  key_name : test-key
  image_name : cirros-0.5.1
  volume_size: 10
  flavor_name : tiny
  server_name : heat01
  zone_server : nova
